jobs:
- template: azure-pipelines-windows.yml
  parameters:
    name: 'Windows_VS2019_x86'
    vmImage: 'windows-2019'
    generator: 'Visual Studio 16 2019'
    arch: 'Win32'
- template: azure-pipelines-windows.yml
  parameters:
    name: 'Windows_VS2019_x64'
    vmImage: 'windows-2019'
    generator: 'Visual Studio 16 2019'
    arch: 'x64'